/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.example;

import my.example.hue.Lights;
import org.apache.avro.file.DataFileReader;
import org.apache.avro.io.DatumReader;
import org.apache.avro.specific.SpecificDatumReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

public class App {

    private static final Logger log = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) throws URISyntaxException, IOException {
        DatumReader<Lights> lightsDatumReader = new SpecificDatumReader<>(Lights.class);
        File file = getFileFromResource("./lights.avro");

        try (DataFileReader<Lights> dataFileReader = new DataFileReader<>(file, lightsDatumReader)) {
            Lights lights = null;
            while (dataFileReader.hasNext()) {
                lights = dataFileReader.next(lights);
                log.info("{}", lights);
            }
        }
    }

    private static File getFileFromResource(String fileName) throws URISyntaxException {
        ClassLoader classLoader = App.class.getClassLoader();
        URL resource = classLoader.getResource(fileName);
        if (resource == null) {
            throw new IllegalArgumentException("file not found! " + fileName);
        } else {
            return new File(resource.toURI());
        }
    }

}
